import { useState } from "react";
import QuizQuestion from "./components/QuizQuestion";
import Summary from "./components/Summary";

function App() {
  return (
    <>
      <div className='flex flex-col justify-center items-center gap-4'>
        <QuizQuestion question={"Prove this transformation is linear"} answerArr={["Answer 1", "Answer 2", "Answer 3"]} id={1} correctAns={"Answer 3"}/>
        {/* <Summary
          summary={
            "Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay "
          }
        /> */}
      </div>
      {/* <div>
        <Summary
          summary={
            "Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay Whatever heres an essay "
          }
        />
      </div> */}
    </>
  );
}

export default App;
